package Entities_Controllers.Battles;

import Entities_Controllers.Bosses.Boss;
import Entities_Controllers.Bosses.BossesRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class BattlesService {

    @Autowired
    private BattlesRepository battlesRepository;

    @Autowired
    private BossesRepository bossRepository;

    // Method to save battles with associated bosses
    public void saveBattlesWithBoss(Battles battles, Boss boss) {
        // Save the Boss entity first to ensure it has an ID generated by the database
        Boss savedBoss = bossRepository.save(boss);

        // Set the saved Boss entity in the Battles entity
        battles.setBoss(savedBoss);

        // Now save the Battles entity
        battlesRepository.save(battles);
    }

    // Other methods related to battles can be added here...
}
